//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rule()
        {
            this.Masses = new HashSet<Mass>();
        }
    
        public System.Guid Id { get; set; }
        public string MassType { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
        public bool Sunday { get; set; }
        public bool I { get; set; }
        public bool II { get; set; }
        public bool III { get; set; }
        public bool IV { get; set; }
        public bool V { get; set; }
        public bool VI { get; set; }
        public bool VII { get; set; }
        public bool VIII { get; set; }
        public bool IX { get; set; }
        public bool X { get; set; }
        public bool XI { get; set; }
        public bool XII { get; set; }
        public bool Week1 { get; set; }
        public bool Week2 { get; set; }
        public string Week3 { get; set; }
        public bool Week4 { get; set; }
        public bool Week5 { get; set; }
        public string WeekLast { get; set; }
        public string CycleType { get; set; }
        public System.Guid ChurchId { get; set; }
        public System.Guid LiturgicalCycleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mass> Masses { get; set; }
        public virtual Church Church { get; set; }
        public virtual LiturgicalCycle LiturgicalCycle { get; set; }
    }
}
