//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public long Id { get; set; }
        public string MassType { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
        public bool Sunday { get; set; }
        public bool I { get; set; }
        public bool II { get; set; }
        public bool III { get; set; }
        public bool IV { get; set; }
        public bool V { get; set; }
        public bool VI { get; set; }
        public bool VII { get; set; }
        public bool VIII { get; set; }
        public bool IX { get; set; }
        public bool X { get; set; }
        public bool XI { get; set; }
        public bool XII { get; set; }
        public bool Week1 { get; set; }
        public bool Week2 { get; set; }
        public string Week3 { get; set; }
        public bool Week4 { get; set; }
        public bool Week5 { get; set; }
        public string WeekLast { get; set; }
        public string CycleType { get; set; }
        public string SingularMass { get; set; }
        public System.DateTime DateBegin { get; set; }
        public System.DateTime DateEnd { get; set; }
        public System.DateTime Hour { get; set; }
        public int DateShift { get; set; }
        public System.DateTime RepeatDateFirst { get; set; }
        public int RepeatDays { get; set; }
        public int RepeatMonths { get; set; }
        public string RepeatFlag { get; set; }
    }
}
